"""empty message

Revision ID: 50e8b13b486f
Revises: 148e25fd8c36
Create Date: 2021-08-08 17:33:17.732182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e8b13b486f'
down_revision = '148e25fd8c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_table', sa.Integer(), nullable=True),
    sa.Column('product_table', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_table'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_table'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cart_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cart_table')
    # ### end Alembic commands ###
